SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, RS.FAVORITES
FROM REST_INFO R
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) RS ON R.FOOD_TYPE = RS.FOOD_TYPE
WHERE R.FAVORITES = RS.FAVORITES
ORDER BY FOOD_TYPE DESC;