SELECT AO.ANIMAL_ID, AO.ANIMAL_TYPE, AO.NAME
FROM ANIMAL_OUTS AO
JOIN (
    SELECT ANIMAL_ID
    FROM ANIMAL_INS AI
    WHERE AI.SEX_UPON_INTAKE LIKE 'Intact%'
) AIS ON AO.ANIMAL_ID = AIS.ANIMAL_ID
WHERE AO.SEX_UPON_OUTCOME LIKE 'Spayed%' OR AO.SEX_UPON_OUTCOME LIKE 'Neutered%'
ORDER BY AO.ANIMAL_ID