SELECT FH.FLAVOR
FROM FIRST_HALF FH
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) AS JS ON FH.FLAVOR = JS.FLAVOR
ORDER BY (FH.TOTAL_ORDER+JS.TOTAL_ORDER) DESC
LIMIT 3;