SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II
JOIN (
    SELECT *
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IN (
                    SELECT ITEM_ID
                    FROM ITEM_INFO
                    WHERE RARITY = 'RARE'
    )
) AS ITS ON II.ITEM_ID = ITS.ITEM_ID
ORDER BY II.ITEM_ID DESC;