SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CH ON C.CAR_ID = CH.CAR_ID
WHERE C.CAR_TYPE = '세단' AND CH.START_DATE LIKE '%-10-%'
ORDER BY C.CAR_ID DESC;