SELECT HG.SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = '2022'
    GROUP BY EMP_NO HAVING MAX(SCORE)
    ORDER BY SCORE DESC
    LIMIT 1
) AS HG
JOIN HR_EMPLOYEES HE ON HG.EMP_NO = HE.EMP_NO
JOIN HR_DEPARTMENT HD ON HE.DEPT_ID = HD.DEPT_ID;